name: Android build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          - name: "ARM32"
            arch: "armeabi-v7a"

          - name: "ARM64"
            arch: "arm64-v8a"

    name: Linux -> Android-${{ matrix.name }}

    steps:
    - name: Clean Disk
      uses: DiligentGraphics/github-action/clean-disk-ubuntu@v8

    - name: Clone repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up build environment
      if:   success()
      uses: DiligentGraphics/github-action/setup-build-env@v8
      with:
        platform: Android

    - name: Build with Gradle
      if:   success()
      env:
        ANDROID_ARCH: ${{ matrix.arch }}
      run: |
        cd $GITHUB_WORKSPACE/DiligentSamples/Android
        chmod +x gradlew
        ./gradlew buildRelease
        echo -e "\nRemaining disk space: $(df -BG / | awk 'NR==2 {print $4}' | sed 's/G//') GB"
